package celestek.hexcraft.client.model.special;

import java.util.List;
import java.util.Optional;

import javax.vecmath.Matrix4f;

import org.apache.commons.lang3.tuple.Pair;

import com.google.common.collect.Lists;

import celestek.hexcraft.utility.HexShapes;
import net.minecraft.block.state.IBlockState;
import net.minecraft.client.renderer.block.model.BakedQuad;
import net.minecraft.client.renderer.block.model.IBakedModel;
import net.minecraft.client.renderer.block.model.ItemCameraTransforms.TransformType;
import net.minecraft.client.renderer.block.model.ItemOverrideList;
import net.minecraft.client.renderer.texture.TextureAtlasSprite;
import net.minecraft.client.renderer.vertex.VertexFormat;
import net.minecraft.util.BlockRenderLayer;
import net.minecraft.util.EnumFacing;
import net.minecraftforge.client.MinecraftForgeClient;
import net.minecraftforge.client.model.PerspectiveMapWrapper;
import net.minecraftforge.common.model.IModelState;
import net.minecraftforge.common.model.TRSRTransformation;

/**
 * A baked model of a special hexagonal prism which uses 1 texture and a base which also uses 1 texture. The base is rendered on the solid layer while the monolith - on the translucent layer. Supports quad caching, matrix and item perspective transforms
 */
public class BakedModelMonolith implements IBakedModel
{
	/**
	 * The item perspective transforms defined under the "transform" tag in the blockstate
	 */
	protected final IModelState state;
	/**
	 * The vertex format in which all of the model's quads should be drawn in
	 */
	protected final VertexFormat format;
	/**
	 * The matrix transforms generated by {@link ModelMonolith}
	 */
	protected final Optional<TRSRTransformation> transform;

	protected final TextureAtlasSprite base, monolith;

	public BakedModelMonolith(IModelState state, VertexFormat format, Optional<TRSRTransformation> transform, TextureAtlasSprite base, TextureAtlasSprite monolith)
	{
		this.state = state;
		this.format = format;
		this.transform = transform;
		this.base = base;
		this.monolith = monolith;
	}

	@Override
	public List<BakedQuad> getQuads(IBlockState state, EnumFacing side, long rand) // Culling?
	{
		List<BakedQuad> quads = Lists.newArrayList();
		// Don't draw anything if faces should be culled
		if(side != null) return quads;
		BlockRenderLayer renderLayer = MinecraftForgeClient.getRenderLayer();
		// Draw the quads
		// Render the base part if on the solid layer
		if(renderLayer == null || renderLayer == BlockRenderLayer.SOLID) HexShapes.MonolithBase.create(quads, this.format, this.transform, null, -1, true, this.base);
		// Render the monolith part if on the translucent layer
		if(renderLayer == null || renderLayer == BlockRenderLayer.TRANSLUCENT) HexShapes.Monolith.create(quads, this.format, this.transform, null, 0, false, this.monolith);
		return quads;
	}

	@Override
	public boolean isAmbientOcclusion()
	{
		return true;
	}

	@Override
	public boolean isGui3d()
	{
		return true;
	}

	@Override
	public boolean isBuiltInRenderer()
	{
		return false;
	}

	@Override
	public TextureAtlasSprite getParticleTexture()
	{
		return this.monolith;
	}

	@Override
	public ItemOverrideList getOverrides()
	{
		return ItemOverrideList.NONE;
	}

	@Override
	public Pair<? extends IBakedModel, Matrix4f> handlePerspective(TransformType transform)
	{
		return PerspectiveMapWrapper.handlePerspective(this, this.state, transform);
	}
}